Main page modify design
kumoh42/futsal-front pull request #12
Opened 2023-08-13 08:21 UTC by JeongHyeon2

왼쪽 진한 회색 부분 글씨 크기 수정
로그아웃 위치 오른쪽 위로 옮기기
달력 넘어갈 때, 1일 따라가기
공백 인식 막기
로그인 버튼 글씨 키우기 & 볼드
로그인 텍스트 버튼 키우기
로그인 페이지 좌측 하단에 Id \ pw 버튼 쪽 누르면 금오사이 홈페이지로 이동기능

2023-08-13 08:34 UTC, qkrwnstlr commented on flutter_front/lib/auth/view/login_view.dart
> +                            onPressed: () async {
동작은 view에서 분리 시키는게 더 좋을꺼 같아요!
그리고 지금처럼 throw만 하는거 보다는 예외 처리를 확실하게 하는게 좋습니다. 지금 저희 같은 경우에는 snack bar를 띄운다던가??

2023-08-13 08:38 UTC, qkrwnstlr commented on flutter_front/lib/common/layout/default_layout.dart
> +                      onPressed: ref.read(authServiceProvider.notifier).logout,
지금은 default layout이니까 이렇게 해도 되지만 나중에 다른 작업하다 dialog를 띄울 일이 있으면 해당 부분은 view에서 분리시켜 주세요!

2023-08-14 06:22 UTC, gimseonjin requested changes

2023-08-14 06:22 UTC, gimseonjin commented on flutter_front/lib/auth/view/login_view.dart
> +                                  'https://kumoh42.com/index.php?mid=main&act=dispMemberSignUpForm');
이런 거 하드 코딩 하지말고 .env로 빼주세요!!

2023-08-14 06:22 UTC, gimseonjin commented on flutter_front/lib/common/layout/default_layout.dart
> +}
가능하면 이런 주석은 남기지 말고 삭제해주세요!!

만약 다시 롤백 해야하면 git log나 github에서 보는 걸로 하는 게 좋을 거 같아요!!

2023-08-14 06:22 UTC, gimseonjin commented on flutter_front/pubspec.lock
> +  flutter: ">=3.10.0"
이런건 가능하면 안바뀌는 게 좋아요!!!

2023-08-14 06:22 UTC, gimseonjin commented on flutter_front/lib/common/layout/default_layout.dart
> +      appBar: title == null
이거 아래 문법으로 해보는 건 어떨까요??

`
appBar: title ?? _CustomAppBar(
              appbarHeight: appbarHeight!,
              leading: leading!,
              leadingWidth: leadingWidth!,
              title: title!,
            )
`

2023-08-16 05:26 UTC, JeongHyeon2 commented on flutter_front/lib/common/layout/default_layout.dart
> +      appBar: title == null
title이 null이면 AppBar가 null이 되어야하는데

title??_CustomAppBar은 title이 null이면 _CustomAppBar를 반환하고, null이 아니면 title이라는 String값을 반환해서
appbar와 type error가 발생해요...

2023-08-16 05:51 UTC, JeongHyeon2 commented on flutter_front/lib/auth/view/login_view.dart
> +                            onPressed: () async {
완료했습니다!!

2023-08-16 05:51 UTC, JeongHyeon2 commented on flutter_front/lib/auth/view/login_view.dart
> +                                  'https://kumoh42.com/index.php?mid=main&act=dispMemberSignUpForm');
옙!

2023-08-16 05:53 UTC, JeongHyeon2 commented on flutter_front/lib/common/layout/default_layout.dart
> +                      onPressed: ref.read(authServiceProvider.notifier).logout,
view와 완벽하게 분리하는 것을 아직 잘 이해하지 못했습니다...ㅠ

2023-08-16 05:53 UTC, JeongHyeon2 commented on flutter_front/lib/common/layout/default_layout.dart
> +}
옙!

2023-08-16 05:53 UTC, JeongHyeon2 commented on flutter_front/pubspec.lock
> +  flutter: ">=3.10.0"
옙!

2023-08-16 12:46 UTC, gimseonjin commented on flutter_front/lib/common/layout/default_layout.dart
> +      appBar: title == null
아 내가 반대로 봤네 title이 있으면 커스텀, null이면 null이어야 하는구나

굳 잡 브로!

2023-08-17 00:23 UTC, JeongHyeon2 commented on flutter_front/lib/common/layout/default_layout.dart
> +                      onPressed: ref.read(authServiceProvider.notifier).logout,
했습니다!

2023-08-17 13:19 UTC, qkrwnstlr commented
LGTM

2023-08-18 01:25 UTC, gimseonjin approved these changes
LGTM

2023-08-18 06:52 UTC, qkrwnstlr commented
LGTM

2023-08-18 06:54 UTC, qkrwnstlr approved these changes

2023-08-18 06:55 UTC, merged